export const BaseColors = {
  orange: "#FA6207",
  brown: "#4C1C00",
  yellow: "#FFD700",
  lightGray: "#ffffff73",
  darkGray: "#333333",
  orangeLight: "#FF7254",
  red: "#FF3B30",
  black: "#121216",
  white: "#FBFAF5",
  lightBlack: "#1a1a1a",
  inputBackground: "#2a2a2a",
  whiteDark: "#F5F5F5",
  borderGray: "#333",
  orangeOpacity: "rgba(255, 60, 0, 0.13)",
  dark: "#000000",
  green: "#34C759",
  blue: "#81b0ff",
  blueDark: "#007AFF",
  gray: "#666",
  grayLight: "rgba(50, 50, 50, 0.24)",
};
export const Colors = {
  dark: {
    title: BaseColors.white,
    background: BaseColors.dark,
    btn: BaseColors.orange,
    disabled: BaseColors.brown,
    ratingStar: BaseColors.yellow,
    dots: BaseColors.gray,
    bgModal: BaseColors.darkGray,
    bookmark: BaseColors.orangeLight,
    text: BaseColors.white,
    input: BaseColors.lightBlack,
    chip: BaseColors.darkGray,
    card: BaseColors.darkGray,
    stats: BaseColors.lightBlack,
    border: BaseColors.darkGray,
    settigsItem: BaseColors.lightBlack,
    settingsSectionTitle: BaseColors.blue,
    placeholder: BaseColors.lightGray,
    inactiveColor: BaseColors.gray,
    activeTab: BaseColors.blueDark,
    emptyStateBackground: BaseColors.lightBlack,
    tabBackground: BaseColors.lightBlack,
    inputBackground: BaseColors.inputBackground,
  },
  light: {
    title: BaseColors.dark,
    background: BaseColors.whiteDark,
    btn: BaseColors.orangeLight,
    disabled: BaseColors.brown,
    ratingStar: BaseColors.yellow,
    dots: BaseColors.gray,
    bgModal: BaseColors.darkGray,
    bookmark: BaseColors.orangeLight,
    text: BaseColors.black,
    input: BaseColors.whiteDark,
    chip: BaseColors.lightGray,
    card: BaseColors.orangeOpacity,
    stats: BaseColors.white,
    border: BaseColors.grayLight,
    settigsItem: BaseColors.white,
    settingsSectionTitle: BaseColors.blueDark,
    placeholder: BaseColors.dark,
    inactiveColor: BaseColors.gray,
    activeTab: BaseColors.blueDark,
    emptyStateBackground: BaseColors.whiteDark,
    tabBackground: BaseColors.whiteDark,
    inputBackground: BaseColors.white,
  },
};
