export const BaseColors = {
  orange: '#FA6207',
  brown: '#4C1C00',
  yellow: '#F2C94C',
  gray: '#828282',
  lightGray: '#E0E0E0',
  darkGray: '#333333',
  orangeLight: '#FF7254',
  red: '#EB2247',
  black: '#121216',
  white: '#FBFAF5',
  lightBlack: '#1F1F1F',
  whiteDark: '#F5F5F5',
  orangeOpacity: 'rgba(255, 60, 0, 0.13)',
  dark: '#000000',
}
export const Colors = {
  dark: {
    title: BaseColors.white,
    background: BaseColors.dark,
    btn: BaseColors.orange,
    disabled: BaseColors.brown,
    ratingStar: BaseColors.yellow,
    dots: BaseColors.gray,
    bgModal: BaseColors.darkGray,
    bookmark: BaseColors.orangeLight,
    text: BaseColors.white,
    input: BaseColors.lightBlack,
    chip: BaseColors.darkGray,
    card: BaseColors.darkGray,
  },
  light: {
    title: BaseColors.dark,
    background: BaseColors.white,
    btn: BaseColors.orangeLight,
    disabled: BaseColors.brown,
    ratingStar: BaseColors.yellow,
    dots: BaseColors.gray,
    bgModal: BaseColors.darkGray,
    bookmark: BaseColors.orangeLight,
    text: BaseColors.black,
    input: BaseColors.whiteDark,
    chip: BaseColors.lightGray,
    card: BaseColors.orangeOpacity,
  },
}
